platform :ios, '8.0'

pod 'AudioToolbox'
pod 'CFNetwork'
pod 'CoreGraphics'
pod 'CoreLocation'
pod 'MobileCoreServices'
pod 'QuartzCore'
pod 'Security'
pod 'StoreKit'
pod 'SystemConfiguration'
pod 'libz'
pod 'libsqlite3'
